-- +goose Up

CREATE TABLE public.observation_store (
  singleton integer PRIMARY KEY CHECK (singleton = 1),
  incarnation text NOT NULL CHECK (length(incarnation) = 32 AND incarnation ~ '^[0-9a-f]{32}$')
);
INSERT INTO public.observation_store VALUES (1, pg_catalog.replace(pg_catalog.gen_random_uuid()::text, '-', ''));
CREATE TABLE public.observation_revisions (
  session_id bytea PRIMARY KEY,
  revision bigint NOT NULL CHECK (revision >= 0)
);

CREATE TABLE public.sessions (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  record bytea NOT NULL,
  workspace_id bytea NOT NULL,
  title bytea NOT NULL,
  created_at text COLLATE "C" NOT NULL,
  updated_at text COLLATE "C" NOT NULL
);
CREATE INDEX sessions_workspace_created_idx ON public.sessions(workspace_id, created_at, id);
CREATE TABLE public.runs (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  session_key bigint NOT NULL REFERENCES public.sessions(row_key),
  status text NOT NULL CHECK (status IN ('pending', 'running', 'interrupted', 'failed', 'completed')),
  provider_id bytea NOT NULL,
  model_id bytea NOT NULL,
  owner_id bytea NOT NULL,
  claim_token bytea NOT NULL,
  lease_until bigint NOT NULL,
  record bytea NOT NULL,
  created_at text COLLATE "C" NOT NULL
);
CREATE INDEX runs_session_status_idx ON public.runs(session_key, status);
CREATE UNIQUE INDEX runs_session_active_unique_idx ON public.runs(session_key) WHERE status IN ('pending', 'running');
CREATE TABLE public.messages (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  session_key bigint NOT NULL REFERENCES public.sessions(row_key),
  run_key bigint NOT NULL REFERENCES public.runs(row_key),
  role text NOT NULL CHECK (role IN ('system', 'user', 'assistant', 'tool')),
  finalized integer NOT NULL CHECK (finalized IN (0,1)),
  record bytea NOT NULL,
  created_at text COLLATE "C" NOT NULL
);
CREATE INDEX messages_replay_idx ON public.messages(session_key, created_at, id);
CREATE INDEX messages_run_key_idx ON public.messages(run_key);
CREATE TABLE public.parts (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  message_key bigint NOT NULL REFERENCES public.messages(row_key),
  session_key bigint NOT NULL REFERENCES public.sessions(row_key),
  run_key bigint NOT NULL REFERENCES public.runs(row_key),
  ordinal bigint NOT NULL,
  kind text NOT NULL CHECK (kind IN ('text', 'reasoning', 'tool_call', 'tool_result', 'file', 'step', 'compaction', 'state', 'provider_state')),
  display_text bytea NOT NULL,
  text_valid integer NOT NULL CHECK (text_valid IN (0,1)),
  record bytea NOT NULL,
  created_at text COLLATE "C" NOT NULL
);
CREATE INDEX parts_replay_idx ON public.parts(session_key, message_key, ordinal, id);
CREATE INDEX parts_message_key_idx ON public.parts(message_key);
CREATE INDEX parts_run_key_idx ON public.parts(run_key);
CREATE TABLE public.tool_calls (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  session_key bigint NOT NULL REFERENCES public.sessions(row_key),
  run_key bigint NOT NULL REFERENCES public.runs(row_key),
  request_message_key bigint NOT NULL REFERENCES public.messages(row_key),
  request_part_key bigint NOT NULL REFERENCES public.parts(row_key),
  result_message_id bytea NOT NULL,
  result_part_id bytea NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'interrupted')),
  name bytea NOT NULL,
  claimed_by bytea NOT NULL,
  claim_token bytea NOT NULL,
  record bytea NOT NULL
);
CREATE INDEX tools_unfinished_idx ON public.tool_calls(run_key, status);
CREATE INDEX tool_calls_request_message_key_idx ON public.tool_calls(request_message_key);
CREATE INDEX tool_calls_request_part_key_idx ON public.tool_calls(request_part_key);
CREATE TABLE public.context_epochs (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  session_key bigint NOT NULL REFERENCES public.sessions(row_key),
  record bytea NOT NULL,
  created_at text COLLATE "C" NOT NULL,
  closed_at text COLLATE "C" NOT NULL
);
CREATE INDEX context_epochs_session_created_idx ON public.context_epochs(session_key, created_at, id);
CREATE TABLE public.model_requests (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  session_key bigint NOT NULL REFERENCES public.sessions(row_key),
  run_key bigint NOT NULL REFERENCES public.runs(row_key),
  assistant_message_id bytea NOT NULL,
  state text NOT NULL CHECK (state IN ('prepared', 'dispatch_started', 'completed', 'failed')),
  attempt bigint NOT NULL,
  step bigint NOT NULL,
  record bytea NOT NULL,
  created_at text COLLATE "C" NOT NULL
);
CREATE UNIQUE INDEX model_requests_run_attempt_step_idx ON public.model_requests(run_key, attempt, step);
CREATE INDEX model_requests_run_created_idx ON public.model_requests(run_key, created_at, id);
CREATE INDEX model_requests_session_key_idx ON public.model_requests(session_key);
CREATE TABLE public.events (
  row_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id bytea NOT NULL UNIQUE,
  session_key bigint NOT NULL REFERENCES public.sessions(row_key),
  run_key bigint NOT NULL REFERENCES public.runs(row_key),
  tool_key bigint REFERENCES public.tool_calls(row_key),
  kind bytea NOT NULL,
  tool_transition text CHECK (tool_transition IS NULL OR tool_transition IN ('pending', 'running', 'terminal')),
  record bytea NOT NULL,
  created_at text COLLATE "C" NOT NULL,
  CHECK ((tool_key IS NULL) = (tool_transition IS NULL))
);
CREATE INDEX events_replay_idx ON public.events(session_key, created_at, id);
CREATE INDEX events_run_key_idx ON public.events(run_key);
CREATE INDEX events_tool_key_idx ON public.events(tool_key);
CREATE UNIQUE INDEX events_tool_transition_unique_idx ON public.events(tool_key, tool_transition) WHERE tool_transition IS NOT NULL;
CREATE UNIQUE INDEX events_run_finished_unique_idx ON public.events(run_key, kind) WHERE kind = pg_catalog.decode('72756e5f66696e6973686564', 'hex');
CREATE INDEX messages_observation_idx ON public.messages(session_key, created_at, id, run_key, role, finalized) WHERE role IN ('user', 'assistant');
CREATE INDEX parts_observation_idx ON public.parts(session_key, message_key, kind, ordinal, id, run_key, text_valid);
CREATE INDEX tools_observation_idx ON public.tool_calls(session_key, run_key, id);

-- +goose StatementBegin
CREATE FUNCTION public.bump_observation(p_session_id bytea) RETURNS void
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
  INSERT INTO public.observation_revisions(session_id, revision) VALUES (p_session_id, 1)
  ON CONFLICT(session_id) DO UPDATE
  SET revision = public.observation_revisions.revision + 1;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION public.bump_session_from_key(p_key bigint) RETURNS void
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
  INSERT INTO public.observation_revisions(session_id, revision)
  SELECT id, 1 FROM public.sessions WHERE row_key = p_key
  ON CONFLICT(session_id) DO UPDATE
  SET revision = public.observation_revisions.revision + 1;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION public.sessions_observation_trigger() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
  IF TG_OP <> 'INSERT' THEN
    PERFORM public.bump_observation(OLD.id);
  END IF;
  IF TG_OP <> 'DELETE' THEN
    PERFORM public.bump_observation(NEW.id);
  END IF;
  RETURN NULL;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION public.owned_observation_trigger() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
  IF TG_OP <> 'INSERT' THEN
    PERFORM public.bump_session_from_key(OLD.session_key);
  END IF;
  IF TG_OP <> 'DELETE' THEN
    PERFORM public.bump_session_from_key(NEW.session_key);
  END IF;
  RETURN NULL;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER sessions_observation_insert AFTER INSERT ON public.sessions FOR EACH ROW EXECUTE FUNCTION public.sessions_observation_trigger();
CREATE TRIGGER sessions_observation_update AFTER UPDATE ON public.sessions FOR EACH ROW EXECUTE FUNCTION public.sessions_observation_trigger();
CREATE TRIGGER sessions_observation_delete AFTER DELETE ON public.sessions FOR EACH ROW EXECUTE FUNCTION public.sessions_observation_trigger();
CREATE TRIGGER runs_observation_insert AFTER INSERT ON public.runs FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER runs_observation_update AFTER UPDATE ON public.runs FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER runs_observation_delete AFTER DELETE ON public.runs FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER messages_observation_insert AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER messages_observation_update AFTER UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER messages_observation_delete AFTER DELETE ON public.messages FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER parts_observation_insert AFTER INSERT ON public.parts FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER parts_observation_update AFTER UPDATE ON public.parts FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER parts_observation_delete AFTER DELETE ON public.parts FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER tool_calls_observation_insert AFTER INSERT ON public.tool_calls FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER tool_calls_observation_update AFTER UPDATE ON public.tool_calls FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
CREATE TRIGGER tool_calls_observation_delete AFTER DELETE ON public.tool_calls FOR EACH ROW EXECUTE FUNCTION public.owned_observation_trigger();
