//go:build postgres_integration

package postgres

import (
	"context"
	"database/sql"
	_ "embed"
	"encoding/json"
	"errors"
	"flag"
	"os"
	"reflect"
	"testing"
	"time"

	"github.com/mattsp1290/eino-agent/internal/testpostgres"
	"github.com/mattsp1290/eino-agent/session"
)

//go:embed migrations/00001_initial.sql
var schemaBaselineSQL string

// Copied from Goose v3.27.3 internal/dialects/postgres.go CreateTable. The
// following migration slice will exercise this shape through Goose itself.
const schemaHistorySQL = `CREATE TABLE public.eino_agent_goose_version (
 id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 version_id bigint NOT NULL, is_applied boolean NOT NULL,
 tstamp timestamp NOT NULL DEFAULT now());
 INSERT INTO public.eino_agent_goose_version(version_id,is_applied) VALUES(0,true);`

var updateSchemaReference = flag.Bool("update-postgres-schema", false, "regenerate the reviewed PostgreSQL catalog fingerprints")

func TestPostgresSchemaVerification(t *testing.T) {
	server := testpostgres.Start(t)
	t.Run("reference", func(t *testing.T) {
		db := server.Database(t).Open(t)
		schemaExec(t, db, schemaHistorySQL)
		bootstrap := catalogFingerprint(schemaCatalog(t, db))
		schemaExec(t, db, schemaBaselineSQL)
		current := catalogFingerprint(schemaCatalog(t, db))
		encoded, err := json.MarshalIndent(struct{ Bootstrap, Current string }{bootstrap, current}, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		encoded = append(encoded, '\n')
		if *updateSchemaReference {
			if err := os.WriteFile("schema_fingerprints.json", encoded, 0o644); err != nil {
				t.Fatal(err)
			}
			return
		}
		if string(encoded) != string(schemaFingerprints) {
			t.Fatal("catalog reference differs; review DDL/catalog changes before explicit regeneration")
		}
	})
	t.Run("states", func(t *testing.T) {
		for _, state := range []schemaState{schemaEmpty, schemaBootstrap, schemaCurrent} {
			db := server.Database(t).Open(t)
			prepareSchema(t, db, state)
			conn := schemaConn(t, db)
			before := schemaCatalog(t, db)
			history := schemaHistory(t, db)
			for range 2 {
				got, err := inspectSchema(t.Context(), conn)
				if err != nil || got != state {
					t.Fatalf("state %d: got %d, %v", state, got, err)
				}
			}
			if !reflect.DeepEqual(before, schemaCatalog(t, db)) || history != schemaHistory(t, db) {
				t.Fatal("verification changed schema or history")
			}
		}
	})
	t.Run("rejection", func(t *testing.T) { testSchemaRejection(t, server) })
	t.Run("readonly", func(t *testing.T) { testSchemaReadOnly(t, server) })
}

func testSchemaRejection(t *testing.T, server *testpostgres.Server) {
	for _, test := range []struct {
		name   string
		state  schemaState
		change string
	}{
		{"foreign_table", schemaEmpty, `CREATE TABLE public.foreign_app(id integer)`},
		{"foreign_function", schemaEmpty, `CREATE FUNCTION public.foreign_app() RETURNS integer LANGUAGE sql AS 'SELECT 1'`},
		{"foreign_type", schemaEmpty, `CREATE TYPE public.foreign_app AS ENUM('foreign')`},
		{"foreign_sequence", schemaEmpty, `CREATE SEQUENCE public.foreign_app`},
		{"baseline_without_history", schemaEmpty, schemaBaselineSQL},
		{"history_without_row", schemaBootstrap, `DELETE FROM public.eino_agent_goose_version`},
		{"malformed_history", schemaBootstrap, `ALTER TABLE public.eino_agent_goose_version ALTER COLUMN is_applied DROP NOT NULL`},
		{"unknown_version", schemaBootstrap, `UPDATE public.eino_agent_goose_version SET version_id=9`},
		{"incomplete_baseline", schemaBootstrap, `CREATE TABLE public.sessions(id bytea)`},
		{"newer_version", schemaCurrent, `INSERT INTO public.eino_agent_goose_version(version_id,is_applied) VALUES(2,true)`},
		{"duplicate_version", schemaCurrent, `INSERT INTO public.eino_agent_goose_version(version_id,is_applied) VALUES(1,true)`},
		{"reversed_history", schemaCurrent, `UPDATE public.eino_agent_goose_version SET version_id=1-version_id`},
		{"unapplied_version", schemaCurrent, `UPDATE public.eino_agent_goose_version SET is_applied=false WHERE version_id=1`},
		{"missing_table", schemaCurrent, `DROP TABLE public.context_epochs`},
		{"missing_index", schemaCurrent, `DROP INDEX public.messages_run_key_idx`},
		{"altered_index", schemaCurrent, `DROP INDEX public.messages_run_key_idx; CREATE INDEX messages_run_key_idx ON public.messages(session_key)`},
		{"missing_trigger", schemaCurrent, `DROP TRIGGER sessions_observation_insert ON public.sessions`},
		{"disabled_trigger", schemaCurrent, `ALTER TABLE public.sessions DISABLE TRIGGER sessions_observation_insert`},
		{"disabled_foreign_key_trigger", schemaCurrent, `DO $$ DECLARE trigger_name text; BEGIN
 SELECT tgname INTO trigger_name FROM pg_catalog.pg_trigger WHERE tgrelid='public.messages'::regclass AND tgisinternal LIMIT 1;
 EXECUTE format('ALTER TABLE public.messages DISABLE TRIGGER %I',trigger_name); END $$;`},
		{"function_body", schemaCurrent, `CREATE OR REPLACE FUNCTION public.bump_observation(p_session_id bytea) RETURNS void LANGUAGE plpgsql SET search_path=pg_catalog AS 'BEGIN RETURN; END;'`},
		{"function_path", schemaCurrent, `ALTER FUNCTION public.bump_observation(bytea) SET search_path=public`},
		{"column_type", schemaCurrent, `ALTER TABLE public.parts ALTER COLUMN ordinal TYPE integer`},
		{"column_nullability", schemaCurrent, `ALTER TABLE public.sessions ALTER COLUMN title DROP NOT NULL`},
		{"column_collation", schemaCurrent, `ALTER TABLE public.sessions ALTER COLUMN created_at TYPE text COLLATE "default"`},
		{"extra_default", schemaCurrent, `ALTER TABLE public.sessions ALTER COLUMN title SET DEFAULT ''::bytea`},
		{"check_constraint", schemaCurrent, `ALTER TABLE public.messages DROP CONSTRAINT messages_finalized_check`},
		{"foreign_key", schemaCurrent, `ALTER TABLE public.messages DROP CONSTRAINT messages_run_key_fkey; ALTER TABLE public.messages ADD CONSTRAINT messages_run_key_fkey FOREIGN KEY(run_key) REFERENCES public.runs(row_key) ON DELETE CASCADE`},
		{"extra_index", schemaCurrent, `CREATE INDEX foreign_app ON public.sessions(title)`},
		{"row_security", schemaCurrent, `ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY`},
		{"identity_mode", schemaCurrent, `ALTER TABLE public.sessions ALTER COLUMN row_key SET GENERATED ALWAYS`},
		{"missing_incarnation", schemaCurrent, `DELETE FROM public.observation_store`},
	} {
		t.Run(test.name, func(t *testing.T) {
			db := server.Database(t).Open(t)
			prepareSchema(t, db, test.state)
			schemaExec(t, db, test.change)
			before := schemaCatalog(t, db)
			history := schemaHistory(t, db)
			_, err := inspectSchema(t.Context(), schemaConn(t, db))
			if !errors.Is(err, session.ErrConflict) {
				t.Fatalf("got %v, want unsupported schema conflict", err)
			}
			if !reflect.DeepEqual(before, schemaCatalog(t, db)) || history != schemaHistory(t, db) {
				t.Fatal("rejected verification changed catalog or history")
			}
		})
	}
}

func testSchemaReadOnly(t *testing.T, server *testpostgres.Server) {
	database := server.Database(t)
	db := database.Open(t)
	prepareSchema(t, db, schemaCurrent)
	conn := schemaConn(t, db)
	if _, err := conn.ExecContext(t.Context(), `SET search_path=public, pg_catalog`); err != nil {
		t.Fatal(err)
	}
	var before string
	if err := conn.QueryRowContext(t.Context(), `SELECT incarnation FROM public.observation_store`).Scan(&before); err != nil {
		t.Fatal(err)
	}
	history := schemaHistory(t, db)
	if state, err := inspectSchema(t.Context(), conn); err != nil || state != schemaCurrent {
		t.Fatalf("non-default search path: %d, %v", state, err)
	}
	var path string
	if err := conn.QueryRowContext(t.Context(), `SHOW search_path`).Scan(&path); err != nil || path != "public, pg_catalog" {
		t.Fatalf("host search path changed: %q, %v", path, err)
	}
	if _, err := conn.ExecContext(t.Context(), `SET search_path=pg_catalog`); err != nil {
		t.Fatal(err)
	}
	if state, err := inspectSchema(t.Context(), conn); err != nil || state != schemaCurrent {
		t.Fatalf("search path excluding public: %d, %v", state, err)
	}
	reopened := database.Open(t)
	if state, err := inspectSchema(t.Context(), schemaConn(t, reopened)); err != nil || state != schemaCurrent {
		t.Fatalf("independent reopen: %d, %v", state, err)
	}
	var after string
	if err := reopened.QueryRowContext(t.Context(), `SELECT incarnation FROM public.observation_store`).Scan(&after); err != nil || before != after || history != schemaHistory(t, reopened) {
		t.Fatal("verification changed identity or history")
	}
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	if _, err := inspectSchema(ctx, conn); !errors.Is(err, context.Canceled) {
		t.Fatalf("canceled verification: %v", err)
	}
}

func prepareSchema(t *testing.T, db *sql.DB, state schemaState) {
	t.Helper()
	if state != schemaEmpty {
		schemaExec(t, db, schemaHistorySQL)
	}
	if state == schemaCurrent {
		schemaExec(t, db, schemaBaselineSQL)
		schemaExec(t, db, `INSERT INTO public.eino_agent_goose_version(version_id,is_applied) VALUES(1,true)`)
	}
}

func schemaExec(t *testing.T, db *sql.DB, query string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), 30*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, query); err != nil {
		t.Fatal(err)
	}
}

func schemaConn(t *testing.T, db *sql.DB) *sql.Conn {
	t.Helper()
	conn, err := db.Conn(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := conn.Close(); err != nil {
			t.Error(err)
		}
	})
	return conn
}

func schemaCatalog(t *testing.T, db *sql.DB) map[string]string {
	t.Helper()
	tx, err := db.BeginTx(t.Context(), &sql.TxOptions{ReadOnly: true, Isolation: sql.LevelRepeatableRead})
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.ExecContext(t.Context(), `SET LOCAL search_path=pg_catalog`); err != nil {
		t.Fatal(err)
	}
	objects, err := readSchemaCatalog(t.Context(), tx)
	if err != nil {
		t.Fatal(err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatal(err)
	}
	return objects
}

func schemaHistory(t *testing.T, db *sql.DB) string {
	t.Helper()
	var exists bool
	if err := db.QueryRowContext(t.Context(), `SELECT to_regclass('public.eino_agent_goose_version') IS NOT NULL`).Scan(&exists); err != nil {
		t.Fatal(err)
	}
	if !exists {
		return "absent"
	}
	var value string
	if err := db.QueryRowContext(t.Context(), `SELECT coalesce(jsonb_agg(to_jsonb(v) ORDER BY id),'[]'::jsonb)::text FROM public.eino_agent_goose_version v`).Scan(&value); err != nil {
		t.Fatal(err)
	}
	return value
}
