package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
)

// schemaReader is the small portion of database/sql used by the catalog
// verifier. The caller supplies a transaction with the catalog search path
// fixed to pg_catalog.
type schemaReader interface {
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
}

// readSchemaCatalog reads stable structure from public. Every query returns a
// stable key and canonical JSON generated by PostgreSQL; data, sequence
// current values, owners, ACLs, catalog OIDs, and statistics are excluded.
func readSchemaCatalog(ctx context.Context, db schemaReader) (map[string]string, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	catalog := make(map[string]string)
	queries := []string{
		`SELECT 'relation:public.' || c.relname,
 json_build_object('kind',c.relkind,'persistence',c.relpersistence,
   'rowSecurity',c.relrowsecurity,'forceRowSecurity',c.relforcerowsecurity,
   'isPartition',c.relispartition)::text
FROM pg_catalog.pg_class AS c
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind NOT IN ('i','I','S')
ORDER BY c.relname`,
		`SELECT 'column:public.' || c.relname || '.' || a.attname,
 json_build_object('attnum',a.attnum,'name',a.attname,
   'type',pg_catalog.format_type(a.atttypid,a.atttypmod),'typmod',a.atttypmod,
   'notNull',a.attnotnull,'default',pg_catalog.pg_get_expr(d.adbin,d.adrelid),
   'identity',a.attidentity,'generated',a.attgenerated,
   'collation',CASE WHEN a.attcollation=0 THEN NULL
     ELSE pg_catalog.quote_ident(cn.nspname)||'.'||pg_catalog.quote_ident(co.collname) END)::text
FROM pg_catalog.pg_class AS c
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
JOIN pg_catalog.pg_attribute AS a ON a.attrelid=c.oid
LEFT JOIN pg_catalog.pg_attrdef AS d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
LEFT JOIN pg_catalog.pg_collation AS co ON co.oid=a.attcollation
LEFT JOIN pg_catalog.pg_namespace AS cn ON cn.oid=co.collnamespace
WHERE n.nspname='public' AND c.relkind IN ('r','p')
  AND a.attnum>0 AND NOT a.attisdropped
ORDER BY c.relname,a.attnum`,
		`SELECT 'constraint:public.' || c.relname || '.' || x.conname,
 json_build_object('definition',pg_catalog.pg_get_constraintdef(x.oid,false),
   'validated',x.convalidated,'deferrable',x.condeferrable,'deferred',x.condeferred)::text
FROM pg_catalog.pg_constraint AS x
JOIN pg_catalog.pg_class AS c ON c.oid=x.conrelid
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND x.conrelid<>0
ORDER BY c.relname,x.conname`,
		`SELECT 'index:public.' || t.relname || '.' || ic.relname,
 json_build_object('definition',pg_catalog.pg_get_indexdef(i.indexrelid),
   'valid',i.indisvalid,'ready',i.indisready,'unique',i.indisunique,
   'primary',i.indisprimary)::text
FROM pg_catalog.pg_index AS i
JOIN pg_catalog.pg_class AS t ON t.oid=i.indrelid
JOIN pg_catalog.pg_namespace AS tn ON tn.oid=t.relnamespace
JOIN pg_catalog.pg_class AS ic ON ic.oid=i.indexrelid
JOIN pg_catalog.pg_namespace AS inn ON inn.oid=ic.relnamespace
WHERE tn.nspname='public' AND inn.nspname='public'
ORDER BY t.relname,ic.relname`,
		`SELECT 'trigger:public.' || c.relname || '.' || t.tgname,
 json_build_object('definition',pg_catalog.pg_get_triggerdef(t.oid,false),
   'enabled',t.tgenabled)::text
FROM pg_catalog.pg_trigger AS t
JOIN pg_catalog.pg_class AS c ON c.oid=t.tgrelid
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND NOT t.tgisinternal
ORDER BY c.relname,t.tgname`,
		`SELECT 'constraint-trigger:public.' || c.relname || '.' || x.conname || '.' || p.proname,
 json_build_object('enabled',t.tgenabled,'type',t.tgtype,
   'deferrable',t.tgdeferrable,'deferred',t.tginitdeferred,
   'function',pn.nspname||'.'||p.proname,'arguments',pg_catalog.encode(t.tgargs,'hex'))::text
FROM pg_catalog.pg_trigger AS t
JOIN pg_catalog.pg_class AS c ON c.oid=t.tgrelid
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
JOIN pg_catalog.pg_constraint AS x ON x.oid=t.tgconstraint
JOIN pg_catalog.pg_proc AS p ON p.oid=t.tgfoid
JOIN pg_catalog.pg_namespace AS pn ON pn.oid=p.pronamespace
WHERE n.nspname='public' AND t.tgisinternal
ORDER BY c.relname,x.conname,p.proname`,
		`SELECT 'function:public.' || p.proname || '(' ||
 pg_catalog.pg_get_function_identity_arguments(p.oid) || ')',
 json_build_object('kind',p.prokind,'language',l.lanname,
   'definition',CASE WHEN p.prokind IN ('f','p','w')
     THEN pg_catalog.pg_get_functiondef(p.oid) END,
   'config',COALESCE(pg_catalog.array_to_json(p.proconfig),'[]'::json),
   'securityDefiner',p.prosecdef,'leakproof',p.proleakproof,
   'strict',p.proisstrict,'volatility',p.provolatile,'parallel',p.proparallel)::text
FROM pg_catalog.pg_proc AS p
JOIN pg_catalog.pg_namespace AS n ON n.oid=p.pronamespace
JOIN pg_catalog.pg_language AS l ON l.oid=p.prolang
WHERE n.nspname='public'
ORDER BY p.proname,pg_catalog.pg_get_function_identity_arguments(p.oid)`,
		`SELECT 'sequence:public.' || c.relname,
 json_build_object('persistence',c.relpersistence,
   'type',pg_catalog.format_type(s.seqtypid,-1),'start',s.seqstart,
   'increment',s.seqincrement,'min',s.seqmin,'max',s.seqmax,
   'cache',s.seqcache,'cycle',s.seqcycle,
   'ownedBy',CASE WHEN ot.relname IS NULL THEN NULL ELSE
     pg_catalog.quote_ident(onm.nspname)||'.'||pg_catalog.quote_ident(ot.relname)||'.'||pg_catalog.quote_ident(oa.attname) END)::text
FROM pg_catalog.pg_sequence AS s
JOIN pg_catalog.pg_class AS c ON c.oid=s.seqrelid
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
LEFT JOIN pg_catalog.pg_depend AS d ON d.classid='pg_catalog.pg_class'::pg_catalog.regclass
 AND d.objid=c.oid AND d.deptype IN ('a','i')
 AND d.refclassid='pg_catalog.pg_class'::pg_catalog.regclass
LEFT JOIN pg_catalog.pg_class AS ot ON ot.oid=d.refobjid
LEFT JOIN pg_catalog.pg_namespace AS onm ON onm.oid=ot.relnamespace
LEFT JOIN pg_catalog.pg_attribute AS oa ON oa.attrelid=ot.oid AND oa.attnum=d.refobjsubid
WHERE n.nspname='public'
ORDER BY c.relname`,
		`SELECT 'rule:public.' || c.relname || '.' || r.rulename,
 json_build_object('definition',pg_catalog.pg_get_ruledef(r.oid,false))::text
FROM pg_catalog.pg_rewrite AS r
JOIN pg_catalog.pg_class AS c ON c.oid=r.ev_class
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND r.rulename<>'_RETURN'
ORDER BY c.relname,r.rulename`,
		`SELECT 'policy:public.' || c.relname || '.' || p.polname,
 json_build_object('permissive',p.polpermissive,'command',p.polcmd,
   'using',pg_catalog.pg_get_expr(p.polqual,p.polrelid),
   'check',pg_catalog.pg_get_expr(p.polwithcheck,p.polrelid),
   'roles',(SELECT COALESCE(json_agg(pg_catalog.pg_get_userbyid(roleid) ORDER BY roleid),'[]'::json)
            FROM pg_catalog.unnest(p.polroles) AS roles(roleid)))::text
FROM pg_catalog.pg_policy AS p
JOIN pg_catalog.pg_class AS c ON c.oid=p.polrelid
JOIN pg_catalog.pg_namespace AS n ON n.oid=c.relnamespace
WHERE n.nspname='public'
ORDER BY c.relname,p.polname`,
		`SELECT 'type:public.' || t.typname,
 json_build_object('kind',t.typtype)::text
FROM pg_catalog.pg_type AS t
JOIN pg_catalog.pg_namespace AS n ON n.oid=t.typnamespace
WHERE n.nspname='public'
  AND (t.typtype IN ('d','e','r','m','p') OR (t.typtype='c' AND t.typrelid=0))
ORDER BY t.typname`,
	}
	for _, query := range queries {
		if err := scanCatalogRows(ctx, db, catalog, query); err != nil {
			return nil, err
		}
	}
	return catalog, nil
}

func scanCatalogRows(ctx context.Context, db schemaReader, catalog map[string]string, query string) (err error) {
	if err := ctx.Err(); err != nil {
		return err
	}
	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return fmt.Errorf("query PostgreSQL schema catalog: %w", err)
	}
	for rows.Next() {
		var key, definition string
		if err = rows.Scan(&key, &definition); err != nil {
			break
		}
		if _, exists := catalog[key]; exists {
			err = errors.New("duplicate schema catalog object")
			break
		}
		catalog[key] = definition
	}
	if err == nil {
		err = rows.Err()
	}
	if closeErr := rows.Close(); closeErr != nil {
		err = errors.Join(err, closeErr)
	}
	if ctxErr := ctx.Err(); ctxErr != nil {
		err = errors.Join(err, ctxErr)
	}
	return err
}
